apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headcni.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headcni.labels" . | nindent 4 }}
data:
  # 使用 host-local IPAM 的配置
  10-headcni.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "tailscale-cni",
      "type": "headcni",
      
      "headscale_url": "{{ .Values.config.headscale.url }}",
      "tailscale_socket": "/var/run/tailscale/tailscaled.sock",
      
      "pod_cidr": "{{ .Values.config.network.podCIDRBase | replace "/16" "/24" }}",
      "service_cidr": "{{ .Values.config.network.serviceCIDR }}",
      
      "ipam": {
        "type": "{{ .Values.config.ipam.type }}",
        "subnet": "{{ .Values.config.network.podCIDRBase | replace "/16" "/24" }}",
        "gateway": "{{ .Values.config.network.podCIDRBase | replace "/16" ".1" | replace "/24" ".1" }}",
        "allocation_strategy": "{{ .Values.config.ipam.strategy }}"
      },
      
      "magic_dns": {
        "enable": true,
        "base_domain": "cluster.local",
        "nameservers": [{{- range $i, $ns := .Values.config.magic_dns.nameservers }}{{- if $i }}, {{- end }}"{{ $ns }}"{{- end }}],
        "search_domains": [{{- range $i, $domain := .Values.config.magic_dns.searchDomains }}{{- if $i }}, {{- end }}"{{ $domain }}"{{- end }}]
      },
      
      "mtu": {{ .Values.config.network.mtu }},
      "enable_ipv6": {{ .Values.config.network.enableIPv6 | default false }},
      "enable_network_policy": {{ .Values.config.network.enableNetworkPolicy | default true }}
    }
  
  # 使用 headcni-ipam 的配置
  10-headcni-ipam.conflist: |
    {
      "cniVersion": "1.0.0",
      "name": "headcni",
      "type": "headcni",
      
      "headscale_url": "{{ .Values.config.headscale.url }}",
      "tailscale_socket": "/var/run/tailscale/tailscaled.sock",
      
      "pod_cidr": "{{ .Values.config.network.podCIDRBase | replace "/16" "/24" }}",
      "service_cidr": "{{ .Values.config.network.serviceCIDR }}",
      
      "ipam": {
        "type": "headcni-ipam",
        "subnet": "{{ .Values.config.network.podCIDRBase | replace "/16" "/24" }}",
        "gateway": "{{ .Values.config.network.podCIDRBase | replace "/16" ".1" | replace "/24" ".1" }}",
        "allocation_strategy": "{{ .Values.config.ipam.strategy }}",
        "routes": [
          {
            "dst": "0.0.0.0/0",
            "gw": "{{ .Values.config.network.podCIDRBase | replace "/16" ".1" | replace "/24" ".1" }}"
          }
        ]
      },
      
      "magic_dns": {
        "enable": true,
        "base_domain": "cluster.local",
        "nameservers": [{{- range $i, $ns := .Values.config.magic_dns.nameservers }}{{- if $i }}, {{- end }}"{{ $ns }}"{{- end }}],
        "search_domains": [{{- range $i, $domain := .Values.config.magic_dns.searchDomains }}{{- if $i }}, {{- end }}"{{ $domain }}"{{- end }}]
      },
      
      "mtu": {{ .Values.config.network.mtu }},
      "enable_ipv6": {{ .Values.config.network.enableIPv6 | default false }},
      "enable_network_policy": {{ .Values.config.network.enableNetworkPolicy | default true }}
    }
  
  # 环境变量配置文件
  headcni.env: |
    # Headscale 配置
    HEADSCALE_URL={{ .Values.config.headscale.url }}
    TAILSCALE_SOCKET={{ .Values.config.tailscale.socket | default "/var/run/tailscale/tailscaled.sock" }}
    
    # 网络配置
    POD_CIDR={{ .Values.config.network.podCIDRBase | replace "/16" "/24" }}
    SERVICE_CIDR={{ .Values.config.network.serviceCIDR }}
    MTU={{ .Values.config.network.mtu }}
    
    # IPAM 配置
    IPAM_TYPE={{ .Values.config.ipam.type }}
    ALLOCATION_STRATEGY={{ .Values.config.ipam.strategy }} 