apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headcni.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "headcni.labels" . | nindent 4 }}
data:
  # Basic configuration
  HEADSCALE_URL: {{ .Values.config.headscale.url | quote }}
  TAILSCALE_MODE: {{ .Values.config.tailscale.mode | quote }}
  TAILSCALE_URL: {{ .Values.config.tailscale.url | quote }}
  TAILSCALE_MTU: {{ .Values.config.tailscale.mtu | quote }}
  TAILSCALE_ACCEPT_DNS: {{ .Values.config.tailscale.acceptDNS | quote }}
  
  # Tailscale socket configuration
  TAILSCALE_SOCKET_NAME: {{ .Values.config.tailscale.socket.name | quote }}
  TAILSCALE_SOCKET_PATH: {{ .Values.config.tailscale.socket.path | quote }}
  
  # Tailscale hostname configuration
  TAILSCALE_HOSTNAME_PREFIX: {{ .Values.config.tailscale.hostname.prefix | quote }}
  TAILSCALE_HOSTNAME_TYPE: {{ .Values.config.tailscale.hostname.type | quote }}
  
  # Tailscale user and tags
  TAILSCALE_USER: {{ .Values.config.tailscale.user | quote }}
  TAILSCALE_TAGS: {{ .Values.config.tailscale.tags | join "," | quote }}
  
  # Network configuration
  POD_CIDR: {{ .Values.config.network.podCIDR | quote }}
  SERVICE_CIDR: {{ .Values.config.network.serviceCIDR | quote }}
  NETWORK_MTU: {{ .Values.config.network.mtu | quote }}
  ENABLE_IPV6: {{ .Values.config.network.enableIPv6 | quote }}
  ENABLE_NETWORK_POLICY: {{ .Values.config.network.enableNetworkPolicy | quote }}
  
  # IPAM configuration
  IPAM_TYPE: {{ .Values.config.ipam.type | quote }}
  IPAM_STRATEGY: {{ .Values.config.ipam.strategy | quote }}
  IPAM_GC_INTERVAL: {{ .Values.config.ipam.gcInterval | quote }}
  
  # DNS configuration
  MAGIC_DNS_ENABLED: {{ .Values.config.dns.magicDNS.enabled | quote }}
  MAGIC_DNS_NAMESERVERS: {{ .Values.config.dns.magicDNS.nameservers | join "," | quote }}
  MAGIC_DNS_SEARCH_DOMAINS: {{ .Values.config.dns.magicDNS.searchDomains | join "," | quote }}
  MAGIC_DNS_OPTIONS: {{ .Values.config.dns.magicDNS.options | join "," | quote }}
  
  # Monitoring configuration
  MONITORING_ENABLED: {{ .Values.config.monitoring.enabled | quote }}
  METRICS_PORT: {{ .Values.config.monitoring.port | quote }}
  METRICS_PATH: {{ .Values.config.monitoring.path | quote }}
  
  # Logging configuration
  LOG_LEVEL: {{ .Values.config.logging.level | default "info" | quote }}
  LOG_FORMAT: {{ .Values.config.logging.format | default "json" | quote }}
  LOG_OUTPUT: {{ .Values.config.logging.output | default "stdout" | quote }} 