# HeadCNI 默认配置文件（最小化，仅保留当前代码使用的字段）

# 基础配置
daemon:
  logLevel: "info"

# HeadScale 配置
headscale:
  url: "https://hs.binrc.com"
  authKey: ""

# Tailscale 配置
tailscale:
  mode: "daemon"
  url: "https://hs.binrc.com"
  socket:
    path: "/var/run/headcni/headcni_tailscale.sock"
  mtu: 1280
  user: "server"
  tags:
    - "tag:control-server"
    - "tag:headcni"

# 网络配置
network:
  podCIDR:
    base: ""
  serviceCIDR: ""
  mtu: 1280
  enableIPv6: false
  enableNetworkPolicy: true

# IPAM 配置
ipam:
  type: "host-local"
  strategy: "sequential"
  gcInterval: "1h"

# DNS 配置
dns:
  magicDNS:
    enabled: true
    nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
    searchDomains:
      - "cluster.local"
    options:
      - "ndots:5"
      - "timeout:2"

# 监控配置
monitoring:
  enabled: true
  port: 8080
  path: "/metrics"